#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "masavo"
email = "stoicboys@gmail.com"

[aliases]
# fetch + rebase
pull = ["util", "exec", "--", "sh", "-c", "jj git fetch && jj rebase -d main"]

st = ["status"]
lgt = ["log", "-n", "10"]
spawn = ["new", "main"]
