# about dein hooks
# Junp to link by 'Leader + b'
# https://qiita.com/delphinus/items/cd221a450fd23506e81a

##################
# init
##################
[[plugins]]
repo = '~/.cache/dein/repos/github.com/Shougo/dein.vim'

##################
# colorschemes
##################
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
'''
# 基準
# あとで読みこんでも問題ないものについて
# - keymaping
# - あとから実行する系
##################
# git
##################
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]] # git command from vim
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap [fugitive]  <Nop>
  nmap <Leader>g [fugitive]
  nnoremap <silent> [fugitive]s :Gstatus<CR><C-w>T:h Fugitive<CR>233<S-G>
  nnoremap <silent> [fugitive]a :Gwrite<CR>
  nnoremap <silent> [fugitive]c :Gcommit-v<CR>
  nnoremap <silent> [fugitive]b :Gblame<CR>
  nnoremap <silent> [fugitive]d :Gdiff<CR>
  nnoremap <silent> [fugitive]h :Glog<CR>
  nnoremap <silent> [fugitive]m :Gstatus<CR>:normal ca<CR>:wq
  nnoremap <silent> [fugitive]r :bufdo e!<CR>

'''
##################
# nerdtree
##################
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nmap <Leader>n <plug>NERDTreeTabsToggle<CR>
  nmap <Leader>f :NERDTreeFind<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

##################
# enhance keybind, mapping
##################
[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  let g:unite_enable_start_insert=1
  let g:unite_source_history_yank_enable =1
  let g:unite_source_file_mru_limit = 200
  nnoremap <silent> ,uy :<C-u>Unite history/yank<CR>
  nnoremap <silent> ,ub :<C-u>Unite buffer<CR>
  nnoremap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
  nnoremap <silent> ,ur :<C-u>Unite -buffer-name=register register<CR>
  nnoremap <silent> ,uu :<C-u>Unite file_mru buffer<CR>
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  let g:ctrlp_map = ''
  nmap <Leader>p :CtrlP<CR>
  nmap <Leader>P :CtrlPClearCache<CR>
  let g:ctrlp_show_hidden = 1
  let g:ctrlp_by_filename = 1
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

[[plugins]]
repo = 'mileszs/ack.vim'
if = '''executable('ag')'''
hook_add = '''
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif
'''

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  vmap v <Plug>(expand_region_expand)
  vmap <C-v> <Plug>(expand_region_shrink)
  let g:expand_region_text_objects = {
      \ 'iw'  :0,
      \ 'iW'  :0,
      \ 'i"'  :1,
      \ 'ib'  :1,
      \ 'iB'  :1
\  }
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  nmap <Leader>b <Plug>(openbrowser-smart-search)
  vmap <Leader>b <Plug>(openbrowser-smart-search)
'''
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-(>'
  let g:winresizer_gui_start_key = '<C-)>'
  noremap <Leader>w :winResizerStartResize<CR>
'''

[[plugins]] # camelCase to snake_case
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = '''
  let g:multi_cursor_quit_key = '<C-C>'
  " disable syntax check
  function! s:multiple_cursors_before()
    if exists(':ALEDisableBuffer')==2
        exe 'ALEDisableBuffer'
    endif
    if exists(':CocDisable')==2
        exe 'CocDisable'
    endif
endfunction

function! s:multiple_cursors_after()
    if exists(':ALEEnableBuffer')==2
        exe 'ALEEnableBuffer'
    endif
    if exists(':CocEnable')==2
        exe 'CocEnable'
    endif
endfunction

augroup multiple_cursors
    autocmd User MultipleCursorsPre  call s:multiple_cursors_before()
    autocmd User MultipleCursorsPost call s:multiple_cursors_after()
augroup END
'''

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  nmap z <Plug>(easymotion-s2)
  vmap z <Plug>(easymotion-s2)
'''

##################
# vim拡張: 見えない系
##################
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1  " enable AutoSave on Vim startup
  let g:auto_save_no_updatetime = 1
  let g:auto_save_in_insert_mode = 0
  let g:autosave_time = 2
'''

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
  nmap j <Plug>(accelerated_jk_gj_position)
  nmap k <Plug>(accelerated_jk_gk_position)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  nnoremap <Leader>q :QuickRun<CR>
'''

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'

##################
# complete
##################
[[plugins]]
repo = 'Shougo/neocomplete.vim'

hook_add = '''
let g:acp_enableAtStartup = 0
let g:neocomplete#sources#syntax#min_keyword_length = 2
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_auto_select = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  " snippet Plugin key-mappings.
  " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  imap <C-j>     <Plug>(neosnippet_expand_or_jump)
  smap <C-j>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-j>     <Plug>(neosnippet_expand_target)

  " SuperTab like snippets behavior.
  " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  "imap <expr><TAB>
  " \ pumvisible() ? "\<C-n>" :
  " \ neosnippet#expandable_or_jumpable() ?
  " \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  " For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif


  let g:neosnippet#snippets_directory='~/.vim/bundle/neosnippet-snippets/snippets/'
"  g:neosnippet#disable_runtime_snippets
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


##################
# vim-tags
##################
[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nnoremap <Leader>t :TagbarToggle<CR>
  let g:tagbar_type_ruby = {
    \ 'kinds' : [
        \ 'm:modules',
        \ 'c:classes',
        \ 'd:describes',
        \ 'C:contexts',
        \ 'f:methods',
        \ 'F:singleton methods'
    \ ]
  \ }
'''

[[plugins]]
repo = 'ervandew/supertab' # methods list with ctags

##################
# outline-desplay
##################
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#branch#enabled = 1
  " see this site: https://github.com/vim-airline/vim-airline/wiki/Screenshots
  let g:airline_theme = 'kalisi'
'''

[[plugins]] # show indent line
repo = 'Yggdroot/indentLine'

####################################
# language specific plugins bellow
####################################

##################
# ruby
##################
[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = ['ruby', 'eruby', 'haml','slim','erb']
depends = ['neocomplete.vim','vimproc.vim']

hook_add = '''
  let g:monster#completion#backend = "solargraph"
  " let g:monster#completion#rcodetools#backend = "async_rct_complete"
  " Set async completion.
  let g:monster#completion#rcodetools#backend = "async_solargraph_complete"
  " let g:monster#completion#rcodetools#backend = "async_rct_complete"
" autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
  if !exists('g:neocomplete#force_omni_input_patterns')
   let g:neocomplete#force_omni_input_patterns = {}
  endif
  let g:neocomplete#force_omni_input_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'

'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'Townk/vim-autoclose'
on_ft = ['ruby']

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = ['ruby']

[[plugins]]
repo = 'ngmy/vim-rubocop'
on_ft = ['ruby']
hook_add = '''
let g:syntastic_ruby_rubocop_exe = 'rbenv exec bundle exec rubocop'
let g:vimrubocop_rubocop_cmd = 'rbenv exec bundle exec rubocop'
" let g:vimrubocop_config = ''
'''

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']


[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

##################
# csv
##################
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['fish']

##################
# markdown
##################
# [[plugins]] # a little heavy for my environment
# repo = 'plasticboy/vim-markdown'
# on_ft = ['markdown','md']

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['markdown','md']
hook_add = '''
  let g:markdown_enable_spell_checking = 0
'''


[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['uml','plantuml']

[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'
on_ft = ['uml','plantuml', 'puml']

[[plugins]]
repo = 'tenfyzhong/tagbar-markdown.vim'
on_ft = ['markdown', 'md']

##################
# javascript
##################
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx'  'javascript.tsx','typescript']


##################
# vue
##################
[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','vue']


##################
# elm
##################
[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = ['elm']


##################
# kotlin
##################
[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

##################
# graphql
##################
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['gql', 'graphql', 'Relay.QL']

##################
# toml
##################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml', 'tml']

[[plugins]] # contextのファイルタイプを判定する
repo = 'Shougo/context_filetype.vim' # 依存関係
on_ft = ['toml', 'tml', 'md']

[[plugins]] # コンテキストが違ったときに、シンタックスを変えられる
repo = 'osyo-manga/vim-precious'
on_ft = ['toml', 'tml']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

